In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df = pd.read_csv('ipl.csv')

In [3]:
df.head()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222

In [4]:
col_to_remove = ['mid','batsman','bowler','striker','non-striker']
df.drop(col_to_remove,axis=1,inplace=True)

In [5]:
# only keeping the teams currently playing in ipl
df['bat_team'].unique()

teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians','Kings XI Punjab','Royal Challengers Bangalore', 
          'Delhi Daredevils', 'Pune Warriors', 'Sunrisers Hyderabad',]

df2 = df[(df['bat_team'].isin(teams)) & df['bowl_team'].isin(teams)]

In [6]:
# checking the shapes before and after we have dropped 
df2.shape,df.shape

((58733, 10), (76014, 10))

In [7]:
# only keeping data after 5 overs completed
df3 = df2[df2['overs']>=5]

In [8]:
df3.shape

(43792, 10)

In [9]:
df3['date'] = pd.to_datetime(df3['date'])

C:\Users\215976\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df3['date'].dtype

dtype('<M8[ns]')

In [11]:
df3.reset_index(inplace=True)

In [13]:
df3.head()

,index,date,venue,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total
0,32,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61,0,5.1,59,0,222
1,33,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.2,59,1,222
2,34,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.3,59,1,222
3,35,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.4,59,1,222
4,36,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.5,58,1,222

In [14]:
encoded_df = pd.get_dummies(data=df3,
                            columns =['bat_team','bowl_team','venue']
                           )

In [15]:
pd.set_option('display.max_columns',None)
encoded_df.head()

,index,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,bat_team_Chennai Super Kings,bat_team_Delhi Daredevils,bat_team_Kings XI Punjab,bat_team_Kolkata Knight Riders,bat_team_Mumbai Indians,bat_team_Pune Warriors,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Pune Warriors,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,venue_Barabati Stadium,venue_Brabourne Stadium,venue_Buffalo Park,venue_De Beers Diamond Oval,venue_Dr DY Patil Sports Academy,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Dubai International Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_Holkar Cricket Stadium,venue_JSCA International Stadium Complex,venue_Kingsmead,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,venue_New Wanderers Stadium,venue_Newlands,venue_OUTsurance Oval,"venue_Punjab Cricket Association IS Bindra Stadium, Mohali","venue_Punjab Cricket Association Stadium, Mohali","venue_Rajiv Gandhi International Stadium, Uppal","venue_Sardar Patel Stadium, Motera",venue_Sawai Mansingh Stadium,venue_Shaheed Veer Narayan Singh International Stadium,venue_Sharjah Cricket Stadium,venue_Sheikh Zayed Stadium,venue_St George's Park,venue_Subrata Roy Sahara Stadium,venue_SuperSport Park,venue_Wankhede Stadium
0,32,2008-04-18,61,0,5.1,59,0,222,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,33,2008-04-18,61,1,5.2,59,1,222,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,34,2008-04-18,61,1,5.3,59,1,222,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,35,2008-04-18,61,1,5.4,59,1,222,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,36,2008-04-18,61,1,5.5,58,1,222,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
df_train = encoded_df[encoded_df['date'].dt.year <= 2016]
df_test = encoded_df[encoded_df['date'].dt.year>= 2017]

In [17]:
x_train = df_train.drop('total',axis=1)
y_train = df_train.total
x_test = df_test.drop('total',axis=1)
y_test = df_test.total

In [25]:
x_train.drop('index',axis=1,inplace=True)
x_test.drop('index',axis=1,inplace=True)

In [28]:
x_train.drop('date',axis=1,inplace=True)
x_test.drop('date',axis=1,inplace=True)

In [29]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41014 entries, 0 to 41013
Data columns (total 54 columns):
runs                                                          41014 non-null int64
wickets                                                       41014 non-null int64
overs                                                         41014 non-null float64
runs_last_5                                                   41014 non-null int64
wickets_last_5                                                41014 non-null int64
bat_team_Chennai Super Kings                                  41014 non-null uint8
bat_team_Delhi Daredevils                                     41014 non-null uint8
bat_team_Kings XI Punjab                                      41014 non-null uint8
bat_team_Kolkata Knight Riders                                41014 non-null uint8
bat_team_Mumbai Indians                                       41014 non-null uint8
bat_team_Pune Warriors                                        41014 non-null uint8
bat_team_Rajasthan Royals                                     41014 non-null uint8
bat_team_Royal Challengers Bangalore                          41014 non-null uint8
bat_team_Sunrisers Hyderabad                                  41014 non-null uint8
bowl_team_Chennai Super Kings                                 41014 non-null uint8
bowl_team_Delhi Daredevils                                    41014 non-null uint8
bowl_team_Kings XI Punjab                                     41014 non-null uint8
bowl_team_Kolkata Knight Riders                               41014 non-null uint8
bowl_team_Mumbai Indians                                      41014 non-null uint8
bowl_team_Pune Warriors                                       41014 non-null uint8
bowl_team_Rajasthan Royals                                    41014 non-null uint8
bowl_team_Royal Challengers Bangalore                         41014 non-null uint8
bowl_team_Sunrisers Hyderabad                                 41014 non-null uint8
venue_Barabati Stadium                                        41014 non-null uint8
venue_Brabourne Stadium                                       41014 non-null uint8
venue_Buffalo Park                                            41014 non-null uint8
venue_De Beers Diamond Oval                                   41014 non-null uint8
venue_Dr DY Patil Sports Academy                              41014 non-null uint8
venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     41014 non-null uint8
venue_Dubai International Cricket Stadium                     41014 non-null uint8
venue_Eden Gardens                                            41014 non-null uint8
venue_Feroz Shah Kotla                                        41014 non-null uint8
venue_Himachal Pradesh Cricket Association Stadium            41014 non-null uint8
venue_Holkar Cricket Stadium                                  41014 non-null uint8
venue_JSCA International Stadium Complex                      41014 non-null uint8
venue_Kingsmead                                               41014 non-null uint8
venue_M Chinnaswamy Stadium                                   41014 non-null uint8
venue_MA Chidambaram Stadium, Chepauk                         41014 non-null uint8
venue_Maharashtra Cricket Association Stadium                 41014 non-null uint8
venue_New Wanderers Stadium                                   41014 non-null uint8
venue_Newlands                                                41014 non-null uint8
venue_OUTsurance Oval                                         41014 non-null uint8
venue_Punjab Cricket Association IS Bindra Stadium, Mohali    41014 non-null uint8
venue_Punjab Cricket Association Stadium, Mohali              41014 non-null uint8
venue_Rajiv Gandhi International Stadium, Uppal               41014 non-null uint8
venue_Sardar Patel Stadium, Motera                            41014 non-null uint8
venue_Sawai Mansingh Stadium                                  41014 non-null uint8
venue_Shaheed Veer Narayan Singh International Stadium        41014 non-null uint8
venue_Sharjah Cricket Stadium                                 41014 non-null uint8
venue_Sheikh Zayed Stadium                                    41014 non-null uint8
venue_St George's Park                                        41014 non-null uint8
venue_Subrata Roy Sahara Stadium                              41014 non-null uint8
venue_SuperSport Park                                         41014 non-null uint8
venue_Wankhede Stadium                                        41014 non-null uint8
dtypes: float64(1), int64(4), uint8(49)
memory usage: 3.8 MB

In [30]:
print(x_train.shape,x_test.shape)

(41014, 54) (2778, 54)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
lin_reg = LinearRegression()
for_reg = RandomForestRegressor(n_estimators=200,max_depth=9,random_state=1,n_jobs=-1)

In [32]:
lin_reg.fit(x_train,y_train)
for_reg.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=9, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=-1, oob_score=False,
                      random_state=1, verbose=0, warm_start=False)

In [33]:
print(lin_reg.score(x_test,y_test))
print(for_reg.score(x_test,y_test))

0.7243311770087998
0.668818701109536

In [34]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [35]:
ridge = Ridge()
parameters = {'alpha':[1e-15,1e-10,1e-8,1e-2,1,5,10,20,30,35,40]}
ridge_regressor = GridSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=5)

In [36]:
ridge_regressor.fit(x_train,y_train)

C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.39094e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.38905e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.38148e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.36453e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.46737e-18): result may not be accurate.
  overwrite_a=True).T

GridSearchCV(cv=5, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20, 30,
                                   35, 40]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [37]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 40}
-332.66986879412326

In [38]:
prediction = ridge_regressor.predict(x_test)

In [39]:
import seaborn as sns
sns.distplot(y_test-prediction)

In [40]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

In [41]:
lasso = Lasso()
parameters = {'alpha':[1e-15,1e-10,1e-8,1e-2,1,5,10,20,30,35,40]}
lasso_regressor = GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(x_train,y_train)

C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4466430.903141312, tolerance: 2808.32382622901
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4504908.489341438, tolerance: 2869.2796198774813
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4775861.994775439, tolerance: 2971.1514774862085
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4496857.887223636, tolerance: 3041.5250804242473
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4589012.134996367, tolerance: 2935.31009807083
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 476071.53916723095, tolerance: 2808.32382622901
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 998832.4316776898, tolerance: 2869.2796198774813
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 976839.4792285776, tolerance: 2971.1514774862085
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 542935.183863515, tolerance: 3041.5250804242473
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 241739.72726863343, tolerance: 2935.31009807083
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 476073.37350432295, tolerance: 2808.32382622901
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 998831.0559755731, tolerance: 2869.2796198774813
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 976838.818698436, tolerance: 2971.1514774862085
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 542933.3722110894, tolerance: 3041.5250804242473
  positive)
C:\Users\215976\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 241739.6641193144, tolerance: 2935.31009807083
  positive)

GridSearchCV(cv=5, error_score=nan,
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20, 30,
                                   35, 40]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [42]:
print(ridge_regressor.score(x_test,y_test))
print(lasso_regressor.score(x_test,y_test))

-277.00180425530846
-263.5512516224416

In [43]:
from sklearn.metrics import r2_score

In [44]:
print(r2_score(y_test,lin_reg.predict(x_test)))
print(r2_score(y_test,for_reg.predict(x_test)))
print(r2_score(y_test,ridge_regressor.predict(x_test)))
print(r2_score(y_test,lasso_regressor.predict(x_test)))

0.7243311770087998
0.6688187011095361
0.7266082427056939
0.7398834999942339

In [ ]:
x_train.head()

In [ ]:
def predict_final_score(batting_team,
                        bowling_team,venue,runs,
                        wickets,overs,runs_last_five,wickets_last_five):

    bat_team_index = np.where(x_train.columns=='bat_team_'+batting_team)[0][0]
    bowl_team_index = np.where(x_train.columns=='bowl_team_'+bowling_team)[0][0]
    venue_index =np.where(x_train.columns=='venue_'+venue)[0][0]
    x = np.zeros(len(x_train.columns))
    x[0] = runs
    x[1] = wickets
    x[2] = overs
    x[3] = runs_last_five
    x[4] = wickets_last_five
    
    if bat_team_index >= 0:
        x[bat_team_index] = 1
    if bowl_team_index >= 0:
        x[bowl_team_index] = 1
    if venue_index > 0:
        x[venue_index] >= 1
    x = x.reshape(1,54)
    return np.round(lasso_regressor.predict(x)[0])

In [ ]:
predict_final_score('Chennai Super Kings','Kings XI Punjab','Dr DY Patil Sports Academy',120,3,15.2,45,0)

In [46]:
from xgboost import XGBRegressor
reg_xg = XGBRegressor(n_estimators=800)

In [47]:
reg_xg.fit(x_train,y_train,
          early_stopping_rounds=5,
          eval_set=[(x_test,y_test)],
          verbose=False)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=800, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [48]:
r2_score(y_test,reg_xg.predict(x_test))

0.6764361381393313